f = open("./88w.cpp", "w+") 
f.write("#include <iostream>\nusing namespace std;\n\nint main(void)\n{\n")
f.write("\tcout << \"请给出一个不多于5位的正整数：\";\n")
f.write("\tint x;\n\tcin >> x;\n")
f.write("\tswitch (x)\n\t{\n")
for i in range(1, 100000):
    if i < 10:
        f.write(f"\t\tcase {i}:\n")
        f.write("\t\t\tcout << \"是1位数\" << endl;\n")
        f.write(f"\t\t\tcout << \"个位数是：{i%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"倒过来是：{i}\" << endl;\n")
        f.write("\t\t\tbreak;\n")
    elif i >=10 and i < 100:
        f.write(f"\t\tcase {i}:\n")
        f.write("\t\t\tcout << \"是2位数\" << endl;\n")
        f.write(f"\t\t\tcout << \"个位数是：{i%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"十位数是：{(i//10)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"倒过来是：{str(i)[::-1]}\" << endl;\n")
        f.write("\t\t\tbreak;\n")
    elif i >=100 and i < 1000:
        f.write(f"\t\tcase {i}:\n")
        f.write("\t\t\tcout << \"是3位数\" << endl;\n")
        f.write(f"\t\t\tcout << \"个位数是：{i%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"十位数是：{(i//10)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"百位数是：{(i//100)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"倒过来是：{str(i)[::-1]}\" << endl;\n")
        f.write("\t\t\tbreak;\n")
    elif i >=1000 and i < 10000:
        f.write(f"\t\tcase {i}:\n")
        f.write("\t\t\tcout << \"是4位数\" << endl;\n")
        f.write(f"\t\t\tcout << \"个位数是：{i%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"十位数是：{(i//10)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"百位数是：{(i//100)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"千位数是：{(i//1000)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"倒过来是：{str(i)[::-1]}\" << endl;\n")
        f.write("\t\t\tbreak;\n")
    elif i >=10000 and i < 100000:
        f.write(f"\t\tcase {i}:\n")
        f.write("\t\t\tcout << \"是5位数\" << endl;\n")
        f.write(f"\t\t\tcout << \"个位数是：{i%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"十位数是：{(i//10)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"百位数是：{(i//100)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"千位数是：{(i//1000)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"万位数是：{(i//10000)%10}\" << endl;\n")
        f.write(f"\t\t\tcout << \"倒过来是：{str(i)[::-1]}\" << endl;\n")
        f.write("\t\t\tbreak;\n")


f.write("\t}\n")
f.write("}\n")
f.close()
